# Generated by Django 3.1.6 on 2022-01-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fengmian', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
    ]
