# Generated by Django 3.1.6 on 2022-01-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fengmian', '0002_auto_20220120_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64)),
                ('access_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
