# Generated by Django 3.1.6 on 2022-01-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fengmian', '0003_adcity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PddUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64)),
                ('ip', models.CharField(max_length=64)),
                ('ua1', models.CharField(max_length=255)),
                ('ua2', models.CharField(max_length=255)),
                ('down_times', models.SmallIntegerField(default=5)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PddVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('feed_id', models.CharField(max_length=255)),
                ('goods_id', models.CharField(max_length=255)),
                ('likes', models.CharField(max_length=255)),
                ('comments', models.CharField(max_length=255)),
                ('publish_time', models.DateTimeField()),
                ('down_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
