# Generated by Django 3.1.6 on 2022-01-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fengmian', '0004_pdduser_pddvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedRgisterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='pdduser',
            name='update_time',
            field=models.CharField(default=27, max_length=8),
            preserve_default=False,
        ),
    ]
